export const SET_CONNECTION = 'SET_CONNECTION';
export const SET_USER_AUTHENTICATION = 'SET_USER_AUTHENTICATION';
export const SET_USER = 'SET_USER';
export const SET_USER_CHATS = 'SET_USER_CHATS';
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
export const UPDATE_CHAT = 'UPDATE_CHAT';
export const UPDATE_JOIN_CHAT = 'UPDATE_JOIN_CHAT';